[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
  #"RUSTSEC-0000-0000",
]

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Unicode-DFS-2016",
  "MPL-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "CC0-1.0",
]
exceptions = [
]

[licenses.private]
ignore = false
registries = [
  #"https://sekretz.com/registry
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
allow = [
  #{ name = "ansi_term", version = "=0.11.0" },
]
deny = [
  #{ name = "ansi_term", version = "=0.11.0" },
]
skip = [
  #{ name = "ansi_term", version = "=0.11.0" },
]
skip-tree = [
  #{ name = "ansi_term", version = "=0.11.0", depth = 20 },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []

[graph]
targets = [
  #{ triple = "x86_64-unknown-linux-musl" },
  #{ triple = "wasm32-unknown-unknown", features = ["atomics"] },
]
